/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contributor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all contributors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of contributors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contributor"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Add new contributor */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContributorPost"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributor/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update contributor by ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContributorPut"];
                };
            };
            responses: {
                /** @description Updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contributor"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Delete contributor by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all experiences */
        get: {
            parameters: {
                query?: {
                    /** @description Expand details by query params */
                    expand?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of experiences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Experience"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Add experience */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperiencePost"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experience/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get experience by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Experience details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Experience"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Update experience */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperiencePut"];
                };
            };
            responses: {
                /** @description Updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Experience"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Delete experience by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all my work */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of my work */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Create a new work */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["schemas-WorkPost"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all my websites work */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of websites */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work/open-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all my open-source contributions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of open-source contributions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work/ui-ux": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all my UI/UX designs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of UI/UX designs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work/3d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all my 3D designs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of 3D designs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-work/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get work details by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Update work details */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["schemas-WorkPut"];
                };
            };
            responses: {
                /** @description Updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["schemas-Work"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Delete work by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Add a new skill */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SkillPost"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill/frontend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get frontend skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of frontend skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill/backend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get backend skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of backend skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill/ui-ux": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get UI/UX skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of UI/UX skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update skill by ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SkillPut"];
                };
            };
            responses: {
                /** @description Updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Delete skill by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Contributor: {
            /** @description Unique identifier for the contributor */
            id?: string;
            /** @description Name of the contributor */
            name: string;
            /** @description Position or role */
            position: string;
            /** @description Optional photo URL */
            photo?: string;
            /** @description Communication link or details */
            communication: string;
        };
        ContributorPost: {
            /** @description Name of the contributor */
            name: string;
            /** @description Position or role */
            position: string;
            /** @description Optional photo URL */
            photo?: string;
            /** @description Communication link or details */
            communication: string;
        };
        ContributorPut: {
            /** @description Name of the contributor */
            name?: string;
            /** @description Position or role */
            position?: string;
            /** @description Optional photo URL */
            photo?: string;
            /** @description Communication link or details */
            communication?: string;
        };
        Error: {
            message?: string;
        };
        Experience: {
            /** @description Unique identifier for the experience */
            id?: string;
            /** @description Role or job title */
            role: string;
            /** @description Name of the organization */
            orgName: string;
            /** @description URL to the organization's logo */
            orgLogoUrl: string;
            /**
             * Format: date-time
             * @description Start date of the experience
             */
            startDate: string;
            /**
             * Format: date-time
             * @description End date of the experience
             */
            endDate: string;
            /** @description Details of the experience */
            description: string;
        };
        ExperiencePost: {
            /** @description Role or job title */
            role: string;
            /** @description Name of the organization */
            orgName: string;
            /** @description URL to the organization's logo */
            orgLogoUrl: string;
            /**
             * Format: date-time
             * @description Start date of the experience
             */
            startDate: string;
            /**
             * Format: date-time
             * @description End date of the experience
             */
            endDate: string;
            /** @description Details of the experience */
            description: string;
        };
        ExperiencePut: {
            /** @description Role or job title */
            role?: string;
            /** @description Name of the organization */
            orgName?: string;
            /** @description URL to the organization's logo */
            orgLogoUrl?: string;
            /**
             * Format: date-time
             * @description Start date of the experience
             */
            startDate?: string;
            /**
             * Format: date-time
             * @description End date of the experience
             */
            endDate?: string;
            /** @description Details of the experience */
            description?: string;
        };
        Work: {
            /** @description Unique identifier for the work */
            id?: string;
            /** @description Title of the work */
            title: string;
            /** @description Short documentation or description */
            quickDoc: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev: string;
            /** @description Creation date of the work */
            creationDate: string;
            /** @description Full documentation */
            doc: string;
            /** @description List of skills/technologies used */
            technologies: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors: components["schemas"]["Contributor"][];
            /** @description Source links */
            src: string[];
            /** @description Total number of images */
            numOfImages: number;
            /** @description URLs for images */
            images: string[];
        };
        WorkPost: {
            /** @description Title of the work */
            title: string;
            /** @description Short documentation or description */
            quickDoc: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev: string;
            /** @description Creation date of the work */
            creationDate: string;
            /** @description Full documentation */
            doc: string;
            /** @description List of skills/technologies used */
            technologies: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors: components["schemas"]["Contributor"][];
            /** @description Source links */
            src: string[];
            /** @description Total number of images */
            numOfImages: number;
            /** @description URLs for images */
            images: string[];
        };
        WorkPut: {
            /** @description Title of the work */
            title?: string;
            /** @description Short documentation or description */
            quickDoc?: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category?: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev?: string;
            /** @description Creation date of the work */
            creationDate?: string;
            /** @description Full documentation */
            doc?: string;
            /** @description List of skills/technologies used */
            technologies?: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors?: components["schemas"]["Contributor"][];
            /** @description Source links */
            src?: string[];
            /** @description Total number of images */
            numOfImages?: number;
            /** @description URLs for images */
            images?: string[];
        };
        Skill: {
            /** @description Unique identifier for the skill */
            id: string;
            /** @description Name of the skill */
            title: string;
            /** @description Icon URL or identifier for the skill */
            icon: string;
            /** @description Optional technology usage details */
            techUsage?: string;
        };
        SkillPost: {
            /** @description Name of the skill */
            title: string;
            /** @description Icon URL or identifier for the skill */
            icon: string;
            /** @description Optional technology usage details */
            techUsage?: string;
        };
        SkillPut: {
            /** @description Name of the skill */
            title?: string;
            /** @description Icon URL or identifier for the skill */
            icon?: string;
            /** @description Optional technology usage details */
            techUsage?: string;
        };
        "schemas-Work": {
            /** @description Unique identifier for the work */
            id?: string;
            /** @description Title of the work */
            title: string;
            /** @description Short documentation or description */
            quickDoc: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev: string;
            /** @description Creation date of the work */
            creationDate: string;
            /** @description Full documentation */
            doc: string;
            /** @description List of skills/technologies used */
            technologies: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors: components["schemas"]["Contributor"][];
            /** @description Source links */
            src: string[];
            /** @description Total number of images */
            numOfImages: number;
            /** @description URLs for images */
            images: string[];
        };
        "schemas-WorkPost": {
            /** @description Title of the work */
            title: string;
            /** @description Short documentation or description */
            quickDoc: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev: string;
            /** @description Creation date of the work */
            creationDate: string;
            /** @description Full documentation */
            doc: string;
            /** @description List of skills/technologies used */
            technologies: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors: components["schemas"]["Contributor"][];
            /** @description Source links */
            src: string[];
            /** @description Total number of images */
            numOfImages: number;
            /** @description URLs for images */
            images: string[];
        };
        "schemas-WorkPut": {
            /** @description Title of the work */
            title?: string;
            /** @description Short documentation or description */
            quickDoc?: string;
            /**
             * @description Category of the work
             * @enum {string}
             */
            category?: "websites" | "open-source" | "ui-ux" | "3d";
            /** @description URL for the preview photo */
            photoPrev?: string;
            /** @description Creation date of the work */
            creationDate?: string;
            /** @description Full documentation */
            doc?: string;
            /** @description List of skills/technologies used */
            technologies?: components["schemas"]["Skill"][];
            /** @description List of contributors */
            contributors?: components["schemas"]["Contributor"][];
            /** @description Source links */
            src?: string[];
            /** @description Total number of images */
            numOfImages?: number;
            /** @description URLs for images */
            images?: string[];
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
